services:
  db:
    image: postgres:16
    container_name: teleestomato_db
    environment:
      POSTGRES_DB: teleestomato
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - teleestomato_data:/var/lib/postgresql/data

volumes:
  teleestomato_data: